      SUBROUTINE MACON
      COMMON /ML5MCO/ URO,SRU,EPS,SQOVFL,TWOU,FOURU,LPAR
C***FIRST EXECUTABLE STATEMENT  MACON
      URO=R1MACH(4)
      SRU=SQRT(URO)
      DD=-LOG10(URO)
      LPAR=0.5*DD
      KE=0.5+0.75*DD
      EPS=10.**(-2*KE)
      SQOVFL=SQRT(R1MACH(2))
      TWOU=2.0*URO
      FOURU=4.0*URO
      RETURN
      END
